workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      vars:
        PACKAGE_NAME: "com.wandaatech.easygo"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android Release
        script: |
          # Generate the release build
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - umwemubi@gmail.com